# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commit < Formula
  desc "Commit helper tool"
  homepage "https://github.com/hasansino/commit"
  version "1.14.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hasansino/commit/releases/download/v1.14.0/commit_1.14.0_macOS_x86_64.tar.gz"
      sha256 "9099bf590571ea5fd0c4dd97e90a4fc17f609f77fd41f91a3fc7abd37e3bb970"

      def install
        bin.install "commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hasansino/commit/releases/download/v1.14.0/commit_1.14.0_macOS_arm64.tar.gz"
      sha256 "ecc0b7a90da6d2638c7b5c30e07d2fef74491c56e4b2405059dd2e0fee83026b"

      def install
        bin.install "commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hasansino/commit/releases/download/v1.14.0/commit_1.14.0_linux_x86_64.tar.gz"
      sha256 "690fc1d5b1515eef03fbee94c23692924db2e86791a2f8feb928e2b3ee911269"
      def install
        bin.install "commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hasansino/commit/releases/download/v1.14.0/commit_1.14.0_linux_arm64.tar.gz"
      sha256 "f3161ed4495670bc56d386d28d44706d50fa39c82c0dcc769641fa80b5f85f84"
      def install
        bin.install "commit"
      end
    end
  end

  test do
    system "#{bin}/commit", "--help"
  end
end
